name: gestion_backend
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: 2.3.0
  bcrypt: ^1.1.3
  cron: ^0.5.1
  dart_jsonwebtoken: ^2.7.1
  dart_mappable: 2.0.3
  envied: ^0.3.0
  logger: ^1.3.0
  mailer: ^6.0.0
  mockito: ^5.4.0
  shelf: 1.4.0
  shelf_cors_headers: ^0.1.4
  shelf_helmet: ^1.1.0
  shelf_router: 1.1.3
  shelf_swagger_ui: ^1.0.0+2
  supabase: ^0.2.9
  watcher: 1.0.2
  envify: any
  uuid: ^3.0.5
  intl: ^0.18.0

dev_dependencies:
  envify_generator: any
  build_runner: ^2.3.3
  dart_mappable_builder: ^2.0.2
  http: 0.13.0
  lints: 2.0.0
  test: 1.23.1
  envied_generator: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

